# Generated by Django 6.0.7 on 2026-07-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('plan', models.CharField(choices=[('byok', 'Bring your own key'), ('managed', 'Managed compute')], max_length=16)),
                ('api_key', models.CharField(blank=True, default='', max_length=256)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('stripe_session_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('pending_key', 'Waiting for API key'), ('ready', 'Ready to provision'), ('provisioned', 'Provisioned')], default='pending_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
