# Generated by Django 6.0.7 on 2026-07-10 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedProvisionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Allowed Provision Email',
                'verbose_name_plural': 'Allowed Provision Emails',
            },
        ),
        migrations.AddField(
            model_name='signup',
            name='provision_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='signup',
            name='provision_url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='signup',
            name='provision_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signup',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('pending_key', 'Waiting for API key'), ('ready', 'Ready to provision'), ('provisioning', 'Provisioning'), ('provisioned', 'Provisioned'), ('provision_failed', 'Provisioning failed')], default='pending_payment', max_length=20),
        ),
    ]
