# Generated by Django 6.0.7 on 2026-07-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0002_allowedprovisionemail_signup_provision_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter (Recommended)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('fireworks', 'Fireworks'), ('gemini', 'Google Gemini')], default='openrouter', max_length=32),
        ),
    ]
