# Generated by Django 6.0.7 on 2026-07-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0003_signup_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingGoogleAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, unique=True)),
                ('tenant_username', models.CharField(max_length=64)),
                ('code_verifier', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
